### ISSUE TITLE
Automatic migration of variables type QUERY not working

### ISSUE THREAD

**Issue by khubaibathar** [grafana/google-bigquery-datasource#152]
Hi,
I would like to report that during the migration from doitintl to grafana bigquery, we noticed that the plugin worked for the new dashboards. However, our existing dashboard use many custom Variables made in settings of the type, QUERY. They were not automatically migrated to the new plugin type. It would be great if this issue can be fixed because otherwise we are still on the old plugin(not maintained now). Is there something already in your list regarding that?

**Comment by zoltanbedi** [comment]
Hi @khubaibathar,

Can you please help me understand your issue? You are not able to migrate the variables query to this plugin?

**Comment by khubaibathar** [comment]
Hi @zoltanbedi , Yes exactly. You can find the attached screenshot for clear idea of what's missing.

<img width="379" alt="Screenshot 2022-11-07 at 08 29 52" src="https://user-images.githubusercontent.com/116792385/200251142-7c6b4fd6-b407-4238-9f57-082725a79280.png">

The Query for these kind of data variables are not being migrated.

**Comment by zoltanbedi** [comment]
Got it thank you @khubaibathar. This is not supported in grafana but should be easy to add. https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/components/AnnotationSettings/AnnotationSettingsEdit.tsx#L47

**Comment by khubaibathar** [comment]
@zoltanbedi , i did not understand what you mentioned.
Could you give me an explanation please. thanks!

**Comment by zoltanbedi** [comment]
@khubaibathar we need to make changes in the grafana core code to support what you are asking for.

**Comment by zoltanbedi** [comment]
I want to have this fixed this week. So if all goes well then next week this could go out.

**Comment by dnnshssmnn** [comment]
Hi @zoltanbedi, thanks a lot for looking into this issue and tackling it.
For updating our BigQuery datasource, we also rely on this being resolved.
Can you provide any update so far?

**Comment by zoltanbedi** [comment]
Let's talk about this because I took a look and it is not as easy as I thought in the first place.

The automatic migration feature that this plugin has works like this. When you change the datasource from the old doitintl bigquery plugin to this one it will copy the query, format and location. This only works for the queries but not for annotations or variable queries.

What do you expect? What should happen? How should this work? @khubaibathar @dnnshssmnn

**Comment by khubaibathar** [comment]
Hi @zoltanbedi, 
The thing that you mentioned is not available in the migration is at least what I need. We have variable queries and we would like to migrate them as well along with the normal queries. 
The annotations and variable queries should also be migrated automatically to avoid our users to do manual and error-prone work.

**Comment by dnnshssmnn** [comment]
Thank you for your quick reply @zoltanbedi.

For us, it would be great if that migration feature would work in the same way for a variable query. 
Meaning: when changing the datasource of the query of the variable to the new bigquery plugin, it should copy the query (and format and location).
Currently it just replaces the old query with an empty one. 

Since I'm not familiar with the underlying concepts, I can't tell how this should work or if it is possible at all. Do you think it is?

**Comment by khubaibathar** [comment]
Hi @zoltanbedi ,

Sorry to ping you again but are there any updates for this feature enhancement. :)

Best,

**Comment by zoltanbedi** [comment]
Thanks for your input @khubaibathar and @dnnshssmnn. Sorry I was busy with other issues. I'll try to tackle this next week. I think what @dnnshssmnn says should be doable. I'll update this issue once I have something.

**Comment by zoltanbedi** [comment]
Hi @khubaibathar and @dnnshssmnn.

I took a look at this and this is not easily doable right now. Variable queires are not the same as the normal data queries. For this to work we need more thinking and planning and with that said the people who are responsible for this should do that.

I'll close this issue here and will open a new feature request in the grafana/grafana repository. I can't promise that this will be picked up in the near future though. Your best option is to copy and paste your query to one datasource to another for now.

https://github.com/grafana/grafana/discussions/62690
