### ISSUE TITLE
Trying to connect BigQuery from Grafana ( Running in GCE)

### ISSUE THREAD

**Issue by jagadeesh-govindarajan-db** [grafana/google-bigquery-datasource#159]
Hi Team,

We are trying to connect from Grafana Dashboard to BIGQUERY data source.  
Grafana v9.1.1 is running on the  GCE VM and installed the BIG QUERY plugin. 

When, I used to select "Authentication Type : GCE Default Service Account" and entered the Google Project ID/Region. When trying to do "SAVE & TEST". It gives the "Cannot connect to BigQuery API".  Refer the below screenshot "Error.png"

GCE Service Account : [gce-sa@db-dev-mpox-tdm.iam.gserviceaccount.com] (Has all the permissions for API and roles). Refer the attached screenshot "Roles.png"

**Comment by zoltanbedi** [comment]
Hi @jagadeesh-govindarajan-db,
I can't see the attached screenshot you mentioned. Can you please reupload it?

**Comment by jagadeesh-govindarajan-db** [comment]
> Hi @jagadeesh-govindarajan-db, I can't see the attached screenshot you mentioned. Can you please reupload it?

I am unable to upload images due to ORG policies. But, this is error i am seeing "ERROR[01-05|10:09:35] Failed to get access token               logger=data-proxy-log error="oauth2: cannot fetch token: 400 Bad Request\nResponse: {\n  \"error\": \"invalid_grant\",\n  \"error_description\": \"reauth related error (invalid_rapt)\",\n  \"error_uri\": \"https://support.google.com/a/answer/9368756\",\n  \"error_subtype\": \"invalid_rapt\"\n}"
"

**Comment by zoltanbedi** [comment]
Hi @jagadeesh-govindarajan-db,
It took some time but I was finally be able to try this out. I'm sorry to say that something is wrong in your side. I just tested with grafana 9.1.0 that I installed from the marketplace in google cloud. I needed to change the service account to the one I have access with bigquery and then it worked. As this issue is not related to the plugin I'm going to close this issue.
