### ISSUE TITLE
Macros failing when used in Alerts

### ISSUE THREAD

**Issue by thomshutt** [grafana/google-bigquery-datasource#204]
The following query works fine when used as the query backing a graph in Grafana:
```
SELECT timestamp_trunc(`analytics.nginx_session_summaries`.`end_session_ts`, hour, 'UTC') AS `end_session_ts`
FROM `analytics.nginx_session_summaries`
WHERE (
  unix_millis(end_session_ts) >= ${__from}
  AND 
  unix_millis(end_session_ts) <= ${__to}
)
```

but when I try to use the same query to create an alert, I get the error:

```
Syntax error: Illegal input character "$" at [4:34], invalidQuery
```

and when I remove the braces to change it to `unix_millis(end_session_ts) >= $__from` then I get:

```
Unexpected macro at [4:34], invalidQuery
```

**Comment by leo-6C656F** [comment]
I'm also encountering this issue. The query works well in Dashboards and Explorer, but fails when I attempt to create an alert. Also if I try to set up an alert from a time series panel, it repeatedly evaluates the same time period due to static values it inserts for the macros. This is not helpful, alerting appears to be broken 😟

**Query Work with Dashboards & Explorer**

```
SELECT 
$__timeGroup(TIMESTAMP_SECONDS(s.ts), '${__interval}') as timestamp,
COUNT(DISTINCT s.id) AS Error
FROM `bigquery.sessions` as s,UNNEST(s.hits) as h, UNNEST(h.events) as e
WHERE CAST(PARTITIONTIME as DATE) BETWEEN CAST(LEFT('${__from:date:iso:YYYY-MM-DD}', 10) as DATE) AND CAST(LEFT('${__to:date:iso:YYYY-MM-DD}', 10) AS DATE)
AND e.event = 'Error'
AND s.ts*1000 BETWEEN $__from  AND $__to
GROUP BY $__timeGroup(TIMESTAMP_SECONDS(s.ts), '${__interval}')
```

**Error if I try to copy paste the query into a new Alert**
<img width="1010" alt="image" src="https://github.com/grafana/google-bigquery-datasource/assets/236545/cd34345b-8b88-4acf-b329-bb206ed5b8fb">


**What gets passed over to BigQuery, you can see it doesn't work with or without braces**
`AND s.ts*1000 BETWEEN ${__from}  AND $__to
`
```
SELECT 
TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(TIMESTAMP_SECONDS(s.ts)), 3600) * 3600) as timestamp,
COUNT(DISTINCT s.id) AS Error
FROM bigquery.sessions` as s,UNNEST(s.hits) as h, UNNEST(h.events) as e
WHERE CAST(PARTITIONTIME as DATE) BETWEEN CAST(LEFT('${__from:date:iso:YYYY-MM-DD}', 10) as DATE) AND CAST(LEFT('${__to:date:iso:YYYY-MM-DD}', 10) AS DATE)
AND e.event = 'Error'
AND s.ts*1000 BETWEEN ${__from}  AND $__to
GROUP BY TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(TIMESTAMP_SECONDS(s.ts)), 3600) * 3600)
```

**Static Data Populated if I make the alert from a panel.** 

```
SELECT 
$__timeGroup(TIMESTAMP_SECONDS(s.ts), '5m') as timestamp,
COUNT(DISTINCT s.id) AS Error
FROM bigquery.sessions` as s,UNNEST(s.hits) as h, UNNEST(h.events) as e
WHERE CAST(PARTITIONTIME as DATE) BETWEEN CAST(LEFT('2023-12-30T18:44:03.899Z', 10) as DATE) AND CAST(LEFT('2023-12-31T00:44:03.899Z', 10) AS DATE)
AND e.event = 'Error'
AND s.ts*1000 BETWEEN 1703961843899  AND 1703983443899
GROUP BY $__timeGroup(TIMESTAMP_SECONDS(s.ts), '5m')
```

**Comment by zoltanbedi** [comment]
Dashboard variables are not supported in alerting. https://community.grafana.com/t/use-dashboard-variables-in-alerts/104315

**Comment by goJacob93** [comment]
Hey, thanks for documenting and replying. 

I have a question regarding an issue I’m encountering while using an older version of Grafana (v8.5.3). My setup currently relies heavily on a substantial number of dashboards and alerts that utilize the deprecated DoiT BigQuery datasource, as well as the legacy alert definitions that involve time macros (or time dashboard variables, as referenced in this discussion).

My goal is to migrate all of these dashboards and alerts to the new datasource. However, I’m facing challenges, particularly with the time macros in the alert rules section. I understand that in more recent versions of Grafana, there’s a shift towards Grafana Alerting, but it seems prudent to first migrate my dashboards and alerts to compatible versions before upgrading from v8.5.3.

In fact, when I attempted to upgrade Grafana without making any changes to the BigQuery datasource, my dashboards stopped functioning correctly. This experience has left me uncertain about the best approach for users like myself, who rely on the legacy alerting system and cannot directly migrate everything to Grafana Alerting due to being on a lower version.

Could you please advise on the recommended solution for transforming current alert rules under these circumstances? Should I continue to rely on the deprecated plugin until a complete migration is feasible, or is there an alternative approach that would facilitate a smoother transition?

Thanks again.
